version: '3'

services:
  app:
    build: ./app/
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
  web-proxy:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  rabbit-mq:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: on-failure
  database:
    build: ./database
    volumes:
      - ./database:/var/lib/postgresql/data
